# This is a config for E2B sandbox template.
# You can use template ID (q1sxnafqtu50igbva3e4) or template name (buildquik-nextjs-el) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("buildquik-nextjs-el") # Sync sandbox
# sandbox = await AsyncSandbox.create("buildquik-nextjs-el") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('buildquik-nextjs-el')

team_id = "abc3cebc-70be-4777-ac9e-1b706c9eec31"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "buildquik-nextjs-el"
template_id = "q1sxnafqtu50igbva3e4"
